<div class="row">
    <div class="col-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="row">
            <div class="jumbotron">
                <form action="" method="GET">
                    <div class="form-group col-lg-6 col-md-6">
                        <label for="id">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               value="<?php echo isset($query['id']) ? $query['id'] : ''; ?>" />
                    </div>
                    <div class="form-group col-lg-6 col-md-6">
                        <label for="type">Type</label>
                        <select id="type" name="type" class="form-control">
                            <option value="ASIN" <?php echo (isset($query['type']) && $query['type'] == 'ASIN' ? 'selected' : ''); ?>>ASIN</option>
                            <option value="SKU" <?php echo (isset($query['type']) && $query['type'] == 'SKU' ? 'selected' : ''); ?>>SKU</option>
                            <option value="UPC" <?php echo (isset($query['type']) && $query['type'] == 'UPC' ? 'selected' : ''); ?>>UPC</option>
                            <option value="EAN" <?php echo (isset($query['type']) && $query['type'] == 'EAN' ? 'selected' : ''); ?>>EAN</option>
                            <option value="ISBN" <?php echo (isset($query['type']) && $query['type'] == 'ISBN' ? 'selected' : ''); ?>>ISBN</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Convert</button>
                </form>
            </div>
        </div>

        <?php
        if ($object !== null ) {
            if ($object->Items->Request->IsValid == 'True') {
                ?>
                <h1>Result</h1>
                <table class="table table-bordered table-striped">
                    <tbody>
                        <tr>
                            <td>Title</td>
                            <td><?php echo $object->Items->Item->ItemAttributes->Title; ?></td>
                        </tr>
                        <tr>
                            <td>Stock</td>
                            <td><?php echo 'New: '
                                    . $object->Items->Item->OfferSummary->TotalNew
                                    . ' Used: ' . $object->Items->Item->OfferSummary->TotalUsed; ?></td>
                        </tr>
                        <tr>
                            <td>Price</td>
                            <td><?php echo 'New: '
                                    . $object->Items->Item->OfferSummary->LowestNewPrice->FormattedPrice
                                    . ' Used: ' . $object->Items->Item->OfferSummary->LowestUsedPrice->FormattedPrice; ?></td>
                        </tr>
                        <tr>
                            <td>Image</td>
                            <td><img src="<?php echo $object->Items->Item->MediumImage->URL; ?>" /></td>
                        </tr>
                        <tr>
                            <td>
                                Product page
                            </td>
                            <td>
                                <?php
                                $params = [
                                    'detailsUrl' => $object->Items->Item->DetailPageURL
                                ];

                                echo $this->partial('pages/product', $params);
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>ASIN</td>
                            <td><?php echo $object->Items->Item->ASIN; ?></td>
                        </tr>
                        <tr>
                            <td>EAN</td>
                            <td><?php echo $object->Items->Item->ItemAttributes->EAN; ?></td>
                        </tr>
                        <tr>
                            <td>ISBN</td>
                            <td><?php echo $object->Items->Item->ItemAttributes->ISBN; ?></td>
                        </tr>
                        <tr>
                            <td>UPC</td>
                            <td><?php echo $object->Items->Item->ItemAttributes->UPC; ?></td>
                        </tr>
                    </tbody>
                </table>
            <?php
            } else {
                ?>
                <div class="alert alert-danger">
                    <?php echo $object->Items->Request->Errors->Error->Message; ?>
                </div>
                <?php
            }
        }
        ?>
    </div>
</div>