<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ASIN 2 EAN</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/open-sans.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h1>ASIN 2 EAN converter</h1>
    <?php echo $this->content; ?>
</div>
</body>
</html>